version: "3"
services:
  activemq:
    image: webcenter/activemq
    container_name: activemq
    ports:
      - 8161:8161
      - 61613:61613
      - 5000:5000
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /data/activemq:/data
      - /var/log/activemq:/var/log/activemq

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    