export const ErrCode = {
    SUCCESSFUL: {
      code: 0,
      message: 'Successful',
    },
    DEFAULT: {
      code: 1,
      message: 'Default error',
    },
    AGENT_NOT_FOUND: {
      code: 3,
      message: 'Tài khoản chưa đăng ký hoặc đã bị khóa',
    },
    DATA_DUPLICATED: {
      code: 1009,
      message:
        'Trùng dữ liệu, vui lòng thay đổi thông tin giao dịch hoặc thử lại sau 2 phút.',
    },
    INVALID_TOKEN: {
      code: 20000,
      message: 'Invalid token',
    },
    INVALID_OTP: {
      code: 20001,
      message: 'OTP không đúng',
    },
    AGENT_INVITED: {
      code: 20002,
      message: 'Agent invited',
    },
    AGENT_REGISTERED: {
      code: 20003,
      message: 'Agent registered',
    },
    FILE_NOT_FOUND: {
      code: 20004,
      message: 'File not found',
    },
    LOTTO_TICKET_INVALID: {
      code: 20005,
      message: 'Invalid lotto ticket',
    },
    LOTTO_TICKET_NOT_READY: {
      code: 20006,
      message: 'Lotto ticket not ready',
    },
    LOTTO_TICKET_IS_PAID: {
      code: 20007,
      message: 'Lotto ticket is paid',
    },
    LOTTO_TICKET_NOT_WIN: {
      code: 20008,
      message: 'Not win',
    },
    LOTTO_RESTRICTED: {
      code: 20009,
      message: 'Restricted',
    },
    CARD_NOT_FOUND: {
      code: 20010,
      message: 'Không tìm thấy thông tin thẻ đã nhập',
    },
    TRANS_COMPLETED: {
      code: 20011,
      message: 'Giao dịch đã hoàn tất trước đó',
    },
    QRCODE_NOT_FOUND: {
      code: 20012,
      message: 'QRCode hết hạn hoặc không tồn tại.',
    },
    AGENT_LOGGED_IN: {
      code: 20013,
      message: 'Tài khoản khác đang sử dụng. Vui lòng thoát tài khoản trước.',
    },
    INVALID_TRANS: {
      code: 20014,
      message:
        'Thông tin giao dịch không chính xác, vui lòng kiểm tra và thực hiện lại.',
    },
    AMOUNT_EXCEEDED: {
      code: 20015,
      message:
        'Số tiền vượt giá giới hạn giao dịch, vui lòng kiểm tra và thực hiện lại.',
    },
    AGENT_LOGIN_INVALID: {
      code: 20016,
      message: 'Tài khoản không hợp lệ, vui lòng kiểm tra và thử lại.',
    },
    FORBIDDEN_AGENT: {
      code: 20017,
      message: 'Số điện thoại đã đăng ký trên ECO Merchant',
    },
    DATA_UPDATED: {
      code: 20018,
      message: 'Thông tin đã được lưu trước đó',
    },
    LINK_CODE_EXPIRED: {
      code: 20019,
      message: 'Mã liên kết đã hết hạn',
    },
    CANCEL_PAYGATE: {
      code: 20020,
      message: 'Hủy giao dịch',
    },
    QRCODE_FAILED: {
      code: 20012,
      message: 'Mã QR đã thanh toán hoặc không hợp lệ. Vui lòng thử lại sau.',
    },
  
    // ------------------ecom -----------------------------
    ECOM_NAPAS_INVALID_AMOUNT: {
      code: 30007,
      message: 'Số tiền thanh toán phải từ 10.000 VND đến 10.000.000 VND',
    },
  
    // ------------------nppv2 ----------------------------
    FAILED: {
      code: -1,
      message: 'Thất bại',
    },
    SUCCESS: {
      code: 0,
      message: 'Thành công',
    },
    BAD_REQUEST: {
      code: 1,
      message: 'Sai tham số',
    },
    LOGIN_FAILED: {
      code: 100,
      message: 'Thông tin đăng nhập không chính xác',
    },
    DATA_NOT_FOUND: {
      code: 101,
      message: 'Không tìm thấy dữ liệu',
    },
    // 3xx: for ecom
    NOT_AVAIL_IN_STOCK: {
      code: 300,
      message: 'Hết hàng',
    },
    PRODUCT_NOT_FOUND: {
      code: 301,
      message: 'Sản phẩm không tồn tại',
    },
    FILE_TOO_BIG: {
      code: 302,
      message: 'File quá lớn',
    },
  };
  
  export const ErrorMessage = {
    0: 'Thành công',
    1001: 'Tài khoản không đủ tiền',
    1002: 'Giao dịch đã khôi phục',
    1003: 'Quá hạn mức số dư',
    1004: 'Quá hạn mức giao dịch',
    1005: 'Yêu cầu quá hạn',
    1006: 'Lỗi hệ thống',
    1007: 'Lỗi hệ thống (db)',
    1008: 'Sai tham số',
    1009: 'Dữ liệu bị trùng',
    1010: 'Không tìm thấy dữ liệu',
    1011: 'Chưa thiết lập password',
    1012: 'Quá số lần sai mật khẩu',
    1013: 'Mật khẩu hết hạn',
    1014: 'Sai mật khẩu',
    1015: 'Trùng mật khẩu cũ',
    1016: 'Mật khẩu đã dùng trước đó',
    1020: 'Dữ liệu bắt buôc không có',
    1021: 'Tham số quá ngắn',
    1022: 'Tham số quá dài',
    1023: 'Tham số không đúng',
    1024: 'Xem lại hệ thống',
    1025: 'Rule đã bị khóa',
    // for telco
    2001: 'Hệ thống đang nghẽn',
    2002: 'Lỗi nhà mạng',
    2003: 'Thuê bao trả sau',
    2004: 'Lỗi nhà mạng',
    2005: 'Giao dịch đang xử lý phía nhà mạng',
    2006: 'Thuê bao trả trước',
    2007: 'Giao dịch xử lý thất bại phía nhà mạng', // khong co ket qua
    2008: 'Lỗi thuê bao mới kích hoạt',
    2009: 'Lỗi thuê bao đã bị khóa',
    2010: 'Số tiền thanh toán chưa đúng với số tiền trên hóa đơn nhà mạng',
    2011: 'Hiện các giao dịch phía nhà mạng đang bị nghẽn, vui lòng thử lại sau',
    2012: 'Thuê bao nạp tiền không hợp lệ',
    2013: 'Thuê bao không sử dụng được kênh nạp tiền này',
    2014: 'Giao dịch đã bị hủy',
    2015: 'Session không hợp lệ',
    2016: 'Thuê bao trả sau không có tài khoản EZPay',
    2017: 'Lỗi thuê bao chưa kích hoạt',
    2018: 'Số tiền giao dịch không hợp lệ',
    // for bank 3000->3100
    3000: 'Yêu cầu nhập OTP',
    3001: 'OTP hết hạn',
    3002: 'Sai OTP',
    3003: 'Sai OTP 3 lần',
    3010: 'Số tiền không hợp lệ',
    3011: 'Thẻ không tồn tại',
    3012: 'Thẻ liên kết đã tồn tại',
    3013: 'Thẻ chưa đăng ký dịch vụ giao dịch trực tuyến',
    3014: 'Không đủ số dư thực hiện giao dịch',
    3015: 'Giao dịch vượt hạn mức cho phép',
    3016: 'Thẻ đã bị khóa',
    3017: 'Ngân hàng từ chối(thẻ hoặc tài khoản đã đóng)',
    3018: 'Thẻ đã hết hạn sử dụng',
    3019: 'Vượt quá giới hạn trong ngày(sai OTP, sai số tiền, số lần sai)',
    3020: 'Sai mật khẩu tĩnh',
    3021: 'Sai tên chủ thẻ',
    3022: 'Sai mã số thẻ',
    3023: 'Sai ngày phát hành thẻ',
    3024: 'Sai ngày hết hạn thẻ',
    3025: 'Thẻ hoặc tài khoản không đủ điều kiện giao dịch',
    3026: 'Sai thông tin xác thực',
    3027: 'Giao dịch thất bại, vui lòng liên hệ ngân hàng phát hành thẻ của bạn',
    3028: 'Số tiền quá nhỏ',
    3029: 'Giao dịch đã bị hủy',
    // check bank card/account
    3030: 'Thẻ/tài khoản không hỗ trợ',
    3031: 'Thẻ/tài khoản không tồn tại',
    3032: 'Thẻ/tài khoản đã bị khóa',
    3033: 'Thẻ/tài khoản không được phép',
    3034: 'Có lỗi xảy ra, vui lòng thử lại',
  
    // for billpay 3100->3199
    3100: 'Hóa đơn không tồn tại',
    3101: 'Số tiền thanh toán không hợp lệ',
    3102: 'Mã Hợp đồng không tồn tại',
    3103: 'Mã giao dịch đã thanh toán',
  
    // for airplane 3200->3300
    3200: 'Số lượng hành khách nhiều hơn mức cho phép(tối đa 9)',
    3201: 'Số lượng người lớn nhỏ hơn số lượng trẻ em',
    3202: 'Kết quả tìm chuyến bay không còn hiệu lực, vui lòng thử lại',
  
    // for card 4
    4000: 'Thẻ đã sử dụng',
    4001: 'Thẻ đã bị khóa',
    4002: 'Thẻ hết hạn sử dụng',
    4003: 'Thẻ chưa kích hoạt',
    4004: 'Mã thẻ và số Serial không khớp',
    4005: 'Thẻ thử quá số lần cho phép',
    4006: 'CardSerial không hợp lệ',
    4007: 'CardCode không hợp lệ',
    4008: 'Thẻ không tồn tại',
    4009: 'Không kiểm tra được tình trạng thẻ',
    4010: 'Thông tin thẻ không hợp lệ',
    4011: 'Tài khoản bị khóa do nhập sai thẻ nhiều lần',
  
    // mã lỗi thông báochuyển qua backup route
    5000: 'Giao dịch thất bại, vui lòng thử lại',
  
    // vimo
    // 6000: 'Thành công', => 0
    // 6001: 'Thất bại', => 103
    6002: 'Tham số không hợp lệ',
    6003: 'Checksum không hợp lệ',
    6004: 'IP đối tác bị khóa hoặc chưa được khai báo',
    6005: 'Đối tác bị khóa hoặc chưa được khai báo',
    6006: 'Tham số chưa chính xác',
    6007: 'Dịch vụ chưa được khai báo',
    6008: 'Sản phẩm chưa được khai báo',
    6009: 'Thuộc tính/Mệnh giá sản phẩm chưa được khai báo',
    6020: 'Kênh chưa được khai báo',
    6021: 'Dịch vụ Nhà cung cấp không hợp lệ',
    6022: 'Mã giao dịch đối tác không được trùng nhau',
    6023: 'Không tìm thấy yêu cầu dịch vụ',
    6024: 'Mã yêu cầu thanh toán không được trùng nhau',
    6025: 'Số dư không đủ để thanh toán',
    6026: 'Mã hóa đơn không chính xác hoặc chưa đến kỳ thanh toán',
    6027: 'Hết thời gian thanh toán',
    6028: 'Mã thanh toán không tồn tại',
    6029: 'Mã thanh toán và số tiền không hợp lệ',
    6030: 'Vé bị block sau khi thanh toán',
    6031: 'Đã thanh toán bởi chi nhánh khác',
    6098: 'Timeout',
    6099: 'Lỗi chưa xác định',
  
    // for mobifone vas
    7001: 'Bạn chưa được kích hoạt sử dụng dịch vụ này',
    7002: 'Bạn đã bị khóa sử dụng dịch vụ này',
    7003: 'Số thuê bao giới thiệu không đúng',
    7004: 'Vượt quá giới hạn giới thiệu dịch vụ',
    7005: 'Thuê bao giới thiệu nằm trong danh sách chặn',
    7006: 'Gói cước giới thiệu có giá thấp hơn gói thuê bao đang sử dụng',
    7007: 'Thuê bao MI/FC có lịch sử hủy gọi trong 30 ngày',
    7008: 'Thuê bao không phải FastConnect',
    7009: 'Thuê bao FastConnect có thời hạn kích hoạt trong 12 tháng',
    7010: 'Thuê bao cần hủy trước khi đăng ký gói CTKM',
    7011: 'Khách hàng đang sử dụng gói cước có giá cao hơn',
    7012: 'Khách hàng đang sử dụng gói cước có giá bằng gói đang đăng ký',
    7013: 'Thuê bao đã từ chối cài đặt dịch vụ này',
    7014: 'Điểm bán vi phạm chính sách SPAM',
    7015: 'Thuê bao được giới thiệu quá nhiều mà chưa xác nhận(tối đa 3 lần)',
  
    // for core
    1: 'Sai thông số',
    3: 'Tài khoản không tồn tại',
    4: 'Tài khoản chưa đăng ký',
    5: 'Tài khoản chưa kích hoạt',
    6: 'Tài khoản tạm khóa',
    7: 'Vi phạm chính sách',
    8: 'Sai mật khẩu',
    9: 'Mật khẩu quá hạn',
    10: 'Mật khẩu đã dùng trước đó',
    11: 'Sai Mật khẩu quá số lần quy định',
    12: 'Trùng mật khẩu',
    13: 'Lỗi dịch vụ(TARGET_NOT_FOUND)',
    14: 'Lỗi dịch vụ(TARGET_NOT_REGISTERED)',
    15: 'Lỗi dịch vụ(TARGET_INACTIVE)',
    16: 'Lỗi dịch vụ(TARGET_SUSPENDED)',
    17: 'Số tiền không đúng',
    18: 'TK đã tồn tại',
    19: 'AGENT_BLACKLISTED',
    20: 'TARGET_BLACKLISTED',
    22: 'TARGET_IS_SELF',
    23: 'Số tiền quá nhỏ',
    24: 'Số tiền quá lớn',
    25: 'Sai số tiền',
    26: 'TARGET_REQUIRED',
    27: 'AGENT_EXPIRED',
    28: 'TARGET_EXPIRED',
    29: 'Sai mật khẩu',
    30: 'AGENT_ACTIVE',
    31: 'AGENT_NOT_PARTY',
    32: 'Yêu cầu quá hạn',
    33: 'Giao dịch reversal',
    34: 'TRANSACTION_NOT_TWO_PARTY',
    35: 'INVALID_STATUS_CHANGE',
    36: 'Giao dịch quá cũ',
    37: 'Giao dịch chưa hoàn tất',
    38: 'Tài khoản ngừng sử dụng',
    39: 'TARGET_STOPPED',
    40: 'AGENT_STARTED',
    41: 'Lỗi kết nối',
    42: 'Sai số điện thoại',
    43: 'Kết nối không tồn tại',
    44: 'Sai voucher',
    45: 'Kết nối timeount',
    46: 'Số tiền ngoài ngưỡng cho phép',
    47: 'Dịch vụ chưa hỗ trợ',
    48: 'BILLPAY_ACCOUNT_INVALID',
    49: 'BANK_OFFLINE',
    50: 'BANK_ERROR',
    51: 'SYNC_NOT_REQUIRED',
    52: 'DEVICE_ALREADY_ACTIVE',
    53: 'CONFIG_UPDATE_NOT_REQUIRED',
    54: 'NOT_DEVICE_OWNER',
    55: 'ALIAS_ALREADY_EXISTS',
    56: 'ALIAS_NOT_FOUND',
    57: 'AGENT_ALREADY_SUSPENDED',
    58: 'AGENT_ALREADY_STOPPED',
    59: 'CANNOT_USE_WALLET_TYPE',
    60: 'SCHEDULE_DISALLOWED',
    61: 'INVALID_SCHEDULE',
    62: 'SCHEDULE_NOT_FOUND',
    63: 'CONFIRM_MULTIPLE_TXNS',
    64: 'AGENT_IS_NOT_SPECIAL',
    66: 'CONNECTION_OFFLINE',
    67: 'CONNECTION_ERROR',
    68: 'OPERATION_NOT_SUPPORTED',
    69: 'AGENT_NOT_WELL_CONFIGURED',
    70: 'AGENT_HAS_TRANSACTIONS',
    71: 'Tài khoản đã bị xóa',
    72: 'Tài khoản dến đã bị xóa',
    73: 'AGENT_HAS_BALANCE',
    74: 'INVALID_PASSWORD_MISMATCH',
    75: 'REVERSAL_FAILED',
    76: 'Trùng tên nhóm',
    77: 'GROUP_NOT_EMPTY',
    78: 'CONFIRM_SAME_INITIATOR',
    103: 'Thất bại',
    250: 'CONFIRM_TRANSFER',
    251: 'CONFIRM_CASHOUT',
    252: 'CONFIRM_SELL',
    253: 'CONFIRM_BILLPAY',
    255: 'CONFIRM_LINK',
    256: 'CONFIRM_JOIN_PARENT',
    257: 'CONFIRM_JOIN_CHILD',
    312: 'MODIFY_WALLET_OK',
    400: 'Giao dịch không tồn tại',
    401: 'TRANSFER_CONFIRM_REJECTED',
    415: 'TRACE_TRANSACTION_NOT_FOUND',
    423: 'Giao dịch đã kết thúc',
    425: 'MESSAGE_TOO_LONG',
    501: 'CANNOT_LINK_TO_SUBAGENT',
    502: 'CANNOT_LINK_TO_SELF',
    503: 'LINK_AGENT_DELETED',
    504: 'CANNOT_JOIN_TO_SELF',
    505: 'AGENTS_ALREADY_JOINED',
    506: 'JOIN_AGENT_DELETED',
    507: 'AGENTS_NOT_JOINED',
    508: 'PURCHASE_ORDER_NUMBER_NOT_UNIQUE',
    509: 'REBATE_AMOUNT_NOT_EXACT',
    510: 'REBATE_AMOUNT_NOT_MULTIPLE',
    511: 'REBATE_AMOUNT_TOO_SMALL',
    520: 'VOUCHER_RECIPIENT_NOT_FOUND',
    521: 'VOUCHER_EXPIRY_DATE_PASSED',
    522: 'VOUCHER_NOT_EXIST',
    523: 'NONDELETED_VOUCHERID_PROVIDERID_EXISTS',
    524: 'VOUCHER_NOT_DELETABLE_STATE',
    525: 'MATCHING_VOUCHER_NOT_FOUND',
    999: 'Lỗi dịch vụ',
  };
  