import * as os from 'os';

export const osHostname = os.hostname().toUpperCase();


export const MobileCmd = {
  HELLO: 1000,
  SET_DEVICE_TOKEN: 1,
  BALANCE: 3,
  TRANSFER: 4,
  TOPUP: 6,
  BILLPAY: 7,
  CHANGE_PASS: 16,
  SYNC_NOTI: 21,
  STANDARD_REPLY: 12,
  SYNC_TRANS: 13,
}

export const QUEUE_BASE_PATTERN = {
  ECOM_MEMBER: `TEST_ECOM_MEMBER`,
  ECOM_RES: `TEST_ECOM_RES`,
  BACKEND_ACK: `BACKEND_ACK`
};

export const QUEUE_PATTERN = {
  ECOM_MEMBER: `${QUEUE_BASE_PATTERN.ECOM_MEMBER}_${osHostname}`,
  ECOM_RES: `${QUEUE_BASE_PATTERN.ECOM_RES}_${osHostname}`,

  BACKEND_ACK: 'BACKEND_ACK'
};

export const QUEUE_DESTINATION = {
  ECOM_MEMBER: `/queue/${QUEUE_PATTERN.ECOM_MEMBER}`,
  ECOM_RES: `/queue/${QUEUE_PATTERN.ECOM_RES}`,

};

export const TOPIC_BASE_PATTERN = {
  ECOM_SERVICE_CONTROL: 'ECOM_SERVICE_CONTROL'
};

export const TOPIC_PATTERN = {
  ECOM_SERVICE_CONTROL: `${TOPIC_BASE_PATTERN.ECOM_SERVICE_CONTROL}`
};

const cmdQueue = {};

export const TOPIC_DESTINATION = {
  ECOM_SERVICE_CONTROL: `/topic/${TOPIC_PATTERN.ECOM_SERVICE_CONTROL}`
};

export const MOBILE_QUEUE_BASE_PATTERN = {
  BACKEND_RES: `BACKEND_RES_CONSUMER`,
}

export const MOBILE_QUEUE_PATTERN = {
  BACKEND_RES: `${MOBILE_QUEUE_BASE_PATTERN.BACKEND_RES}_${osHostname}`,
}

export const MOBILE_QUEUE_DESTINATION = {
  BACKEND_RES: `/queue/${MOBILE_QUEUE_PATTERN.BACKEND_RES}`,
}


cmdQueue[MobileCmd.HELLO] = MOBILE_QUEUE_DESTINATION.BACKEND_RES;

export const COMMAND_QUEUE = cmdQueue;
