import * as os from 'os';

export const osHostname = os.hostname().toUpperCase();


export const MobileCmd = {
  HELLO: 1000,
  SET_DEVICE_TOKEN: 1,
  STANDARD_REPLY: 12,
  SYNC_TRANS: 13,
  ECOM_MEMBER: 14
}

export const QUEUE_BASE_PATTERN = {
  ECOM_MEMBER: `TEST_ECOM_MEMBER`,
  ECOM_RES: `TEST_ECOM_RES`,
  BACKEND_ACK: `BACKEND_ACK`,
  HELLO: `HELLO`,
};

export const QUEUE_PATTERN = {
  ECOM_MEMBER: `${QUEUE_BASE_PATTERN.ECOM_MEMBER}_${osHostname}`,
  ECOM_RES: `${QUEUE_BASE_PATTERN.ECOM_RES}_${osHostname}`,
  HELLO:  `${QUEUE_BASE_PATTERN.HELLO}_${osHostname}`,

  BACKEND_ACK: 'BACKEND_ACK'
};

export const QUEUE_DESTINATION = {
  ECOM_MEMBER: `/queue/${QUEUE_PATTERN.ECOM_MEMBER}`,
  ECOM_RES: `/queue/${QUEUE_PATTERN.ECOM_RES}`,
  HELLO: `/queue/${QUEUE_PATTERN.HELLO}`,

};

export const TOPIC_BASE_PATTERN = {
  ECOM_SERVICE_CONTROL: 'ECOM_SERVICE_CONTROL'
};

export const TOPIC_PATTERN = {
  ECOM_SERVICE_CONTROL: `${TOPIC_BASE_PATTERN.ECOM_SERVICE_CONTROL}`
};

const cmdQueue = {};

export const TOPIC_DESTINATION = {
  ECOM_SERVICE_CONTROL: `/topic/${TOPIC_PATTERN.ECOM_SERVICE_CONTROL}`
};

export const MOBILE_QUEUE_BASE_PATTERN = {
  BACKEND_RES: `BACKEND_RES_CONSUMER`,
  HELLO_RES: `HELLO_RES_CONSUMER`,
}

export const MOBILE_QUEUE_PATTERN = {
  BACKEND_RES: `${MOBILE_QUEUE_BASE_PATTERN.BACKEND_RES}_${osHostname}`,
  HELLO_RES: `${MOBILE_QUEUE_BASE_PATTERN.HELLO_RES}_${osHostname}`,
}

export const MOBILE_QUEUE_DESTINATION = {
  BACKEND_RES: `/queue/${MOBILE_QUEUE_PATTERN.BACKEND_RES}`,
  HELLO_RES: `/queue/${MOBILE_QUEUE_PATTERN.HELLO_RES}`,
}


cmdQueue[MobileCmd.HELLO] = QUEUE_PATTERN.HELLO;

export const COMMAND_QUEUE = cmdQueue;
