import * as os from 'os';

export const osHostname = os.hostname().toUpperCase();

export const QUEUE_BASE_PATTERN = {
  ECOM_MEMBER: `TEST_ECOM_MEMBER`,
  ECOM_RES: `TEST_ECOM_RES`,
  BACKEND_ACK: `BACKEND_ACK`
};

export const QUEUE_PATTERN = {
  ECOM_MEMBER: `${QUEUE_BASE_PATTERN.ECOM_MEMBER}_${osHostname}`,
  ECOM_RES: `${QUEUE_BASE_PATTERN.ECOM_RES}_${osHostname}`,

  BACKEND_ACK: 'BACKEND_ACK'
};

export const QUEUE_DESTINATION = {
  ECOM_MEMBER: `/queue/${QUEUE_PATTERN.ECOM_MEMBER}`,
  ECOM_RES: `/queue/${QUEUE_PATTERN.ECOM_RES}`,

};

export const TOPIC_BASE_PATTERN = {
  ECOM_SERVICE_CONTROL: 'ECOM_SERVICE_CONTROL'
};

export const TOPIC_PATTERN = {
  ECOM_SERVICE_CONTROL: `${TOPIC_BASE_PATTERN.ECOM_SERVICE_CONTROL}`
};

export const TOPIC_DESTINATION = {
  ECOM_SERVICE_CONTROL: `/topic/${TOPIC_PATTERN.ECOM_SERVICE_CONTROL}`
};
